#!/usr/bin/env node
/* LemonMaid Cleaning site generator.
   Usage: node build.js
   Output: docs/ (ready for GitHub Pages, "deploy from /docs"). */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT = path.join(ROOT, 'docs');
const SRC = path.join(ROOT, 'src');
const { BIZ, CITIES } = require('./src/site');

const pages = [
  require('./src/pages/home'),
  ...require('./src/pages/services'),
  ...require('./src/pages/landers'),
  ...require('./src/pages/cities'),
  ...require('./src/pages/blog'),
  ...require('./src/pages/misc'),
];

/* Clean output dir */
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

/* Write pages */
for (const page of pages) {
  const dest = path.join(OUT, page.path);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, page.html);
}

/* Static assets */
const copy = (from, to) => {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
};
fs.mkdirSync(path.join(OUT, 'styles'), { recursive: true });
fs.mkdirSync(path.join(OUT, 'scripts'), { recursive: true });
copy(path.join(SRC, 'css/main.css'), path.join(OUT, 'styles/main.css'));
copy(path.join(SRC, 'js/main.js'), path.join(OUT, 'scripts/main.js'));

for (const f of ['favicon.ico', 'favicon-32x32.png', 'favicon-16x16.png', 'apple-touch-icon.png']) {
  copy(path.join(SRC, 'assets', f), path.join(OUT, f));
}
fs.mkdirSync(path.join(OUT, 'images'), { recursive: true });
for (const f of ['logo.png', 'logo.svg']) {
  copy(path.join(SRC, 'assets', f), path.join(OUT, 'images', f));
}
// WebP variants + 1200w JPEGs, pre-generated by tools/optimize-images.js
for (const f of fs.readdirSync(path.join(SRC, 'assets/optimized'))) {
  copy(path.join(SRC, 'assets/optimized', f), path.join(OUT, 'images', f));
}

/* sitemap.xml — same URL set as the original site */
const urls = [
  '/', '/services', '/deep-cleaning-columbus-ohio', '/move-out-cleaning-columbus-ohio',
  '/airbnb-cleaning-columbus-ohio', '/pricing', '/about', '/booking', '/contact-us', '/blog',
  '/blog/how-much-does-house-cleaning-cost-columbus-ohio',
  '/blog/deep-clean-vs-standard-clean',
  '/blog/how-to-prepare-for-a-cleaning-service',
  ...CITIES.map((c) => `/house-cleaning-${c.slug}-ohio`),
];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls.map((u) => `  <url><loc>${BIZ.domain}${u}</loc></url>`).join('\n')}
</urlset>
`;
fs.writeFileSync(path.join(OUT, 'sitemap.xml'), sitemap);

fs.writeFileSync(path.join(OUT, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${BIZ.domain}/sitemap.xml\n`);
fs.writeFileSync(path.join(OUT, '.nojekyll'), '');

/* llms.txt — a concise, factual summary for AI answer engines */
fs.writeFileSync(path.join(OUT, 'llms.txt'), `# LemonMaid Cleaning

> Locally owned residential cleaning company serving Columbus, Ohio and surrounding suburbs
> (Dublin, Hilliard, Powell, Lewis Center, Upper Arlington, Bexley, Gahanna, New Albany, Westerville).

## Services and starting prices
- Standard house cleaning: from $100 (recurring weekly, bi-weekly, monthly, or one-time)
- Deep cleaning: from $180 (adds inside windowpanes, hand-detailed baseboards, tile/grout detail)
- Move-in/move-out cleaning: from $200 (adds inside cabinets, drawers, fridge, freezer, stove)
- Airbnb / short-term rental turnover: from $80 (linens, staging, restocking)

## Key facts
- Phone (call/text): (614) 756-2656 · Email: support@lemonmaidcleaning.com
- Hours: 8:00 AM–8:00 PM, 7 days a week
- Online booking with instant quote: ${BIZ.domain}/booking
- All cleaners are background-checked, trained, and insured; eco-friendly products
- 100% satisfaction guarantee: free re-clean within 24 hours, or refund
- Free rescheduling/cancellation with 24 hours' notice; no contracts

## Pages
- Services: ${BIZ.domain}/services
- Pricing: ${BIZ.domain}/pricing
- Contact: ${BIZ.domain}/contact-us
`);

fs.writeFileSync(path.join(OUT, 'CNAME'), 'www.lemonmaidcleaning.com\n');

console.log(`Built ${pages.length} pages → docs/`);
